// @ts-nocheck
// This file is autogenerated by Firebase Studio. Do not edit manually.
import { initializeApp, getApps, getApp, type FirebaseApp, type FirebaseOptions } from 'firebase/app';
import { getFirestore, type Firestore } from 'firebase/firestore';
import { getAuth, type Auth } from 'firebase/auth';

const firebaseConfig: FirebaseOptions = {"projectId":"studio-4985838886-a6fd7","appId":"1:69181687762:web:e6ebba32f8f20e32ce6a0b","apiKey":"AIzaSyDU42dOnHboQEawP5IHv5tgN8kgETVvH5A","authDomain":"studio-4985838886-a6fd7.firebaseapp.com","measurementId":"","messagingSenderId":"69181687762","storageBucket":"studio-4985838886-a6fd7.appspot.com"};

export function initializeFirebase(config: FirebaseOptions = firebaseConfig) {
  const apps = getApps();
  if (apps.length > 0) {
    const app = getApp();
    return {
      firebaseApp: app,
      firestore: getFirestore(app),
      auth: getAuth(app),
    };
  }
  const firebaseApp = initializeApp(config);
  const firestore = getFirestore(firebaseApp);
  const auth = getAuth(firebaseApp);
  return { firebaseApp, firestore, auth };
}
